
Format

# All
PUBLIC_IP_1
PUBLIC_IP_2
    .
    .
    .
PUBLIC_IP_N

# Groups
[web] # Gropu of web managed nodes
PUBLIC_IP
[Database] # Group of DB managed nodes
DB PUBLIC_IP

eg:

127.9.8.3
34.3.34.5

If Username Applicable Use as:
username@PUBLIC_IP

eg:

ubuntu@3.3.34.34




